name: blockchain_simples
description: Um blockchain simples implementado em Dart
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.3

dev_dependencies:
  test: ^1.24.0 